### ISSUE TITLE
how to run get_coref_and_dep_data.py

### ISSUE THREAD

**Issue by lizhenping** [YuxiXie/SG-Deep-Question-Generation#14]
the advice allennlp==1.0.0, but when I run the code, give an error:
"allennlp.common.checks.ConfigurationError: key "token_embedders" is required at location "model.text_field_embedder.""
i turn the 
allennlp==0.9.0,
spacy==2.1.9,
and install en-core-web-sm 2.2.5 by run python -m spacy download en_core_web_sm,
the allnnlp turn it's code of 1.0.0, this is just for advice

**Comment by ljcnh** [comment]
I also encountered this problem, have you solved it? How to solve it? Looking forward to your answer.

**Comment by YuxiXie** [comment]
Hi here! Thanks for asking. The problem seems to come from the update of allennlp.
You may need to install `allennlp==0.9.0` instead with `overrides==3.1.0`.
We've also updated the paths to the predictors in `get_coref_and_dep_data.py`.
Thanks!

**Comment by qjncxj** [comment]
Do you mean that we should install allenlp==0.9.0, and uninstall overrides==3.1.0, right?  and update the following four paths to the latest version:
dependency_parser = Predictor.from_path(...)
coref_reslt = Predictor.from_path(...)
ner_tagger = Predictor.from_path(...)
sr_labeler = Predictor.from_path(...)

**Comment by YuxiXie** [comment]
> Do you mean that we should install allenlp==0.9.0, and uninstall overrides==3.1.0, right? and update the following four paths to the latest version: dependency_parser = Predictor.from_path(...) coref_reslt = Predictor.from_path(...) ner_tagger = Predictor.from_path(...) sr_labeler = Predictor.from_path(...)

Sorry for the ambiguity, but you need to install both `allenlp==0.9.0` and `overrides==3.1.0`, which means `allennlp==1.0.0` should be uninstalled due to their update. 
And the four predictors' paths are up-to-date for now. They can work in our codes at the present except for some corner cases (e.g., some sentences which are too long),  which you may observe when encountering the `ipdb` breakpoint(s).

**Comment by qjncxj** [comment]
thanks for your accurate and professional reply.



| |
***@***.***
|
|
***@***.***
|




---- Replied Message ----
| From | ***@***.***> |
| Date | 07/19/2022 22:58 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [YuxiXie/SG-Deep-Question-Generation] how to run get_coref_and_dep_data.py (Issue #14) |

Do you mean that we should install allenlp==0.9.0, and uninstall overrides==3.1.0, right? and update the following four paths to the latest version: dependency_parser = Predictor.from_path(...) coref_reslt = Predictor.from_path(...) ner_tagger = Predictor.from_path(...) sr_labeler = Predictor.from_path(...)

Sorry for the ambiguity, but you need to install both allenlp==0.9.0 and overrides==3.1.0, which means allennlp==1.0.0 should be uninstalled due to their update.
And the four predictors' paths are up-to-date for now. They can work in our codes at the present except for some corner cases (e.g., some sentences which are too long), which you may observe when encountering the ipdb breakpoint(s).

**Comment by qjncxj** [comment]
I cannot download en_core_web_sm==2.2.5， Can we use its more high version like "en_core_web_sm-2.3.0.tar.gz"?  My main configuration are as follows:
allenlp==0.9.0     
overrides==3.1.0   
spacy==2.1.9       
en_core_web_sm==2.3.0

**Comment by qjncxj** [comment]
> 

Could you tell us where can I download en-core-web-sm 2.2.5? Thanks.

**Comment by qjncxj** [comment]
error! allennlp-models 1.0.0 requires allennlp==1.0.0, but you have allennlp 0.9.0 which is incompatible.

**Comment by qjncxj** [comment]
> download

wget https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.2.5/en_core_web_sm-2.2.5.tar.gz
