### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by Frankszc** [YuxiXie/SG-Deep-Question-Generation#4]
Hello, thanks for your work and patience.
I wonder that how long time I need when train the classifier and generator using one GPU, I found maybe it's a little long when I try to run the code. One week for classifier and one week for generator, two weeks totally. Is there any advice to speed up the training process?
And when I adjust the argument of -gpus, (e.g. 0 1), I found the training process is stopped, has this happened when you train?
Thanks a lot again!

**Comment by YuxiXie** [comment]
Hi, @Frankszc, you'd better adopt early stopping for training, _i.e._, stop training when the performance on dev dataset obviously gets worse, so that you don't need to wait until all epoches get finished.
And I'm sorry for that our current implementation doesn't support multi-gpu training (due to the format of the model input). So you can only use one gpu to train and run the model.

**Comment by Frankszc** [comment]
ok，thanks for your reply!
