### ISSUE TITLE
Memory Requirements

### ISSUE THREAD

**Issue by yokee06** [YuxiXie/SG-Deep-Question-Generation#5]
Hello,

Could you suggest the required memory requirements?
When running the preprocessing script, the program crashes at loading Glove vectors. I am running it on a GCP instance with 50 GB of RAM.

Also, could you advise on how to use this model on custom documents?

Regards,
Yokesh

**Comment by teacherpeterpan** [comment]
Hi Yokesh, 

I am Liangming. We run our code on a Linux server that has 256GB RAM, but I think a normal Linux server with 128 GB RAM would be enough to run our codes. If you do have memory issues, you could try to revise our preprocessing script: to read the GLOVE file one line at a time, this should save a lot of memory but will increase the processing time. 

To run our code on a custom dataset, you need to first process your documents so that they have the same json format as ours. You could find how to get the input json files at [https://github.com/YuxiXie/SG-Deep-Question-Generation/tree/master/build-semantic-graphs/preprocess](https://github.com/YuxiXie/SG-Deep-Question-Generation/tree/master/build-semantic-graphs/preprocess), including "data.json" (in particular, "data.train.json" & "data.valid.json"), "dp.json" and "crf_rsltn.json". 

Thanks, 
Liangming

**Comment by yokee06** [comment]
Hello Liangming,

Thanks for the response!

I will try refactoring the script. May I know if you have tried BERT or similar embeddings instead of Glove?
Also, it is mentioned that transformer support is there in the repository. Could you tell on how to use it?

Regards,
Yokesh
